#########################
##   General Settings  ##
#########################

#This command will make it so ArcheCore will provide its own Help system, and in doing so
#override the standard /help of Bukkit. Useful as players instinctively use /help
override.help.command: true

#Enable a tertiary lookup mode for help files, namely the Wikipages
enable.wiki.lookup: true

#Setting this to true allows players to use the 'old' LotC commands such as /char, /card, /setage
#The /persona command and all its parameters will work regardless, and have identical function.
enable.legacy.commands: true

#If true, Players can set a 16 character 'prefix' that will precede their Persona name in Chat.
enable.persona.prefix: true

#Setting to modify the Bukkit Display Name functionality to reflect a Persona's name
#If true, a Player's display name will be the Persona name (and prefix, if available) 
modify.player.displayname: false

#Provide in minutes, the cooldown between changing a Persona's name
#Permission node 'archecore.persona.quickrename' ignores this delay.
name.change.delay: 2880

#Provide, in minutes, the cooldown between switching Personas
#Permission node 'archecore.persona.quickswitch' ignores this delay.
persona.change.delay: 120

#If this is true, Personas that have switched (and are thus teleported to their new location)
#Will be re-teleported if they happen to take damage within 40 ticks of arriving at their new location
#This is to save them from possible danger or vastly changed terrain since their last session
teleport.to.rescue: false

#Show players their current XP values and xp needed for next level.
#mods with 'archecore.admin' will always see these
show.exp.values: false

#Whether or not to use the packaged Racial Bonuses in this plugin
enable.racial.bonuses: true

#You can also select which Skill XP bonuses to activate or deactivate
bonus.xp.racial: true
bonus.xp.playtime: true
bonus.xp.autoage: true

#Provide a time, in days, within which Persona files will be preloaded (Personas will not be unloaded if >0)
persona.cache.time: 0

#The current roleplay name of the world we are in
server.world.name: world

#########################
## New Persona Options ##
#########################

#Provide, in minutes, the amount of time a new Persona gets 'Newbie Protection' (provide 0 to turn off)
#Personas under newbie protection can neither attack nor get attacked by other players.
#Permission node 'archecore.persona.nonewbie' ignores this delay
persona.newbie.protect: 0

#Provide, in minutes, the amount of time a new PLAYER gets Newbie notification
#This notification displays a player's greenhorn status in their character cards, encouraging older
#players to be more understanding and friendly as they learn the ropes of the server
newbie.notification: 0

#Provide whether or not new Personas should be teleported back to spawn 
new.persona.to.spawn: true

#You can specify the preferred world name to look for in the teleportation of new Personas to spawn.
#If this world is invalid the Persona will be teleported to the spawn location of the player's current world instead
preferred.spawn.world: world

#########################
##   Economy Settings  ##
#########################

enable.economy: true

currency.name.singular: Minas
currency.name.plural: Minas

#Provide, in percent, the amount of Minas that the Persona will be penalized for dying.
fraction.lost.on.death: 0

#NB: Beginner allowance is for the first Persona of a new player only, not for every new persona
first.persona.money: 100

#This will require Players to be close to one another before they are able to use '/money pay'  
require.pay.proximity: true

#########################
##   Other Settings    ##
#########################

#Debug mode outputs internal information and timings to console
enable.debug.mode: false
