#########################
##   General Settings  ##
#########################

#This command will make it so ArcheCore will provide its own Help system, and in doing so
#override the standard /help of Bukkit. Useful as players instinctively use /help
override.help.command: true

#Enable a tertiary lookup mode for help files, namely the Wikipages
enable.wiki.lookup: true

#Setting this to true allows players to use the 'old' LotC commands such as /char, /card, /setname
#The /persona command and all its parameters will work regardless, and have identical function.
enable.legacy.commands: true

#How much persona slots a player is able to unlock.
#amount of slots that are locked is dependent on permission nodes instead.
persona.slots.maximum: 6

#If true, Players can set a 16 character 'prefix' that will precede their Persona name in Chat.
enable.persona.prefix: true

#Setting to modify the Bukkit Display Name functionality to reflect a Persona's name
#If true, a Player's display name will be the Persona name (and prefix, if available) 
modify.player.displayname: false

#Provide in minutes, the cooldown between changing a Persona's name
#Permission node 'archecore.persona.quickrename' ignores this delay.
name.change.delay: 2880

#Provide, in minutes, the cooldown between switching Personas
#Permission node 'archecore.persona.quickswitch' ignores this delay.
persona.change.delay: 30

#If this is true, Personas that have switched (and are thus teleported to their new location)
#Will be re-teleported if they happen to take damage within 40 ticks of arriving at their new location
#This is to save them from possible danger or vastly changed terrain since their last session
teleport.to.rescue: false

#Show players their current XP values and xp needed for next level.
#mods with 'archecore.admin' will always see these
show.exp.values: false

#Whether or not to use the packaged Racial Bonuses in this plugin
enable.racial.bonuses: true

#The current roleplay name of the world we are in
server.world.name: world

#Whether or not to adjust the swing timer for races
racial.swing.timer: true

#Whether or not to add an ender chest to the Persona menu for easy access
persona.menu.enderchest: false

#Provide a time, in hours, within which a Persona's full fatigue bar should decrease down to 0
#If provided time is 0, the Fatigue system is disabled (fatigue handler calls will do nothing)
persona.fatigue.restore: 22

#Blockregistry entries that are older than this threshold will be removed on start up.
blockregistry.delete.days: 30

#Whether or not the BlockRegistry should remove blocks that have "custom data" attached
remove.custom.blocks: true

#########################
##   Bungee Settings   ##
#########################

#When multiple ArcheCores are in different bungee servers there will be some desync between them, especially when it comes
#to maintaining the immutable permanant increasing persona id.
#While this may change in the future ensure that this is set to FALSE for all but ONE instance of ArcheCore on the network.
can.create.personas: true

#########################
##    Skin Settings    ##
#########################

#This is the account which will be used to aggregate skins and refresh them so they continue to work.
skin:
  username: username
  password: password


#########################
## New Persona Options ##
#########################

#Provide, in minutes, the amount of time a new Persona gets 'Newbie Protection' (provide 0 to turn off)
#Personas under newbie protection can neither attack nor get attacked by other players.
#Permission node 'archecore.persona.nonewbie' ignores this delay
persona.newbie.protect: 0

#Provide, in minutes, the amount of time a new PLAYER gets Newbie notification
#This notification displays a player's greenhorn status in their character cards, encouraging older
#players to be more understanding and friendly as they learn the ropes of the server
newbie.notification: 0

#Provide whether or not new Personas should be teleported back to spawn 
new.persona.to.spawn: true

#You can specify the preferred world name to look for in the teleportation of new Personas to spawn.
#If this world is invalid the Persona will be teleported to the spawn location of the player's current world instead
preferred.spawn.world: world

#Provide, in days, the time within which recently created Personas cannot be deleted
#Creation dialog will output an error message if delete attempts are made in this time period
#Permission node 'archecore.persona.quickkill' ignores this delay.
persona.permakill.delay: 7

#########################
##   Economy Settings  ##
#########################

enable.economy: true

currency.name.singular: Minas
currency.name.plural: Minas

#Provide, in percent, the amount of Minas that the Persona will be penalized for dying.
fraction.lost.on.death: 0

#NB: Beginner allowance is for the first Persona of a new player only, not for every new persona
first.persona.money: 100

#This will require Players to be close to one another before they are able to use '/money pay'
require.pay.proximity: true

#########################
##   Saving Settings   ##
#########################

#Settings for Consumer. These are performance optimization settings and should not be adjusted
#unless you are very familiar with ArcheCore code.
#"Changing config settings"
#Time for each run of the consumer
consumer.run.time: 1000
#Force the consumer to process a minimum of the following transactions
consumer.force.process.minimum: 20
#Delay between consumer runs.
consumer.run.delay: 10
#Whether or not to create a Java Timer or use AsyncTaskScheduler in Bukkit
consumer.use.bukkit.scheduler: true
#The warning size of the queue, when it reaches this threshhold it will warn about overload.
consumer.queue.warning.size: 1000

#Enable the Consumer debug mode which will forward a large amount of info related to tasks into Console.
#enable.debug.mode will enable some basic messages however on the Consumer.
consumer.debug: false

#Checking this to true will force ArcheCore to use MySQL for it's SQLHandler, making all saving mechanisms save into
#a MySQL database. If false ArcheCore will use a SQLite instance
enable.mysql: false

#login info for the MySQL instance, required if the above is true
mysql:
  #The username for the mysql connection
  user: user
  #The port to use for making the connection
  port: 3306
  #The password for the username for this database
  password: password
  #The IP address of the database
  host: localhost
  #The database to use
  database: archecore

#########################
##   Other Settings    ##
#########################

#Debug mode outputs internal information and timings to console
enable.debug.mode: false
