name: ArcheCore
main: net.lordofthecraft.arche.ArcheCore
author: Arche
version: ${project.version}
api-version: 1.13
depends: [Tythan]

commands:
   archehelp:
      description: Obtain help on various aspects of this Server! 
      usage: /<command> for a list of topics. Gain Help with /<command> [topic] 
   helpmenu: 
      description: Obtain Help in a convenient menu format!
   persona:
      description: Manage your Persona or Roleplay Character
      usage: Invalid syntax! Use /<command> help for a list of commands
      permission: archecore.mayuse
      permission-message: §4Insufficient Permission for this command
      aliases: [pers,prs,ps,p]
   newbies:
     description: Allows you to scan for nearby new personas
     usage: This command can only be run from ingame.
     permission: archecore.command.newbies
     permission-message: §4Insufficient Permission for this command
     aliases: [newbie, new, n, ne]
   beaconme:
      description: Open the ArcheCore Beacon menu
      permission: archecore.command.beaconme
      permission-message: §4Insufficient Permission for this command
      aliases: [bme, me]    
   arsql:
      description: Execute SQL statements from ingame
   arclone:
      description: Queue a database clone
      usage: /<command> [true/false]
      permission: archecore.admin
      permission-message: §4Insufficient Permission for this command
   card: 
      description: Legacy command. Added for tab-complete purposes.
      usage: Please type /<command> <player>@<persona>
   realname:
      description: get the current Minecraft Username from a Persona name.
      permission: archecore.mayuse
      permission-message: §4Insufficient Permission for this command
      aliases: [name, nick]
   money:
      description: interact with the Persona-based money balance
      permission: archecore.money
      permission-message: §4Insufficient Permission for this command
      aliases: mn
      usage: Invalid syntax! Use /<command> help for a list of commands
   namelog:
      usage: /<command> [player name/uuid]
      description: interact with the Persona-based money balance
      permission: archecore.mod.persona
      permission-message: §4Insufficient Permission for this command
   racespawn:
      usage: /<command> [race]
      description: Set the spawn of a race.
      permission: archecore.mod.persona
      permission-message: §4Insufficient Permission for this command
   showitem:
      permission: archecore.mayuse
      description: show item in hand to player
   wikisign:
      usage: /<command>
      description: Make a wikisign?
      permission: archecore.mod.sign
      permission-message: §4Insufficient Permission for this command
   attribute:
      usage: /<command> help
      description: Edit the attributes of an online player.
      permission: archecore.admin
      aliases: [attr, att, attri, atr]
      permission-message: §4Insufficient Permission for this command
   skin:
      usage: Please see /<command> help for a list of commands
      description: store and load skins
   date:
      aliases: [currentdate, lotcdate, calendar]
      description: Displays calendar date.
   durabilityboost:
      description: Add a modddurabilityboosted durability boost for the held item
      permission: archecore.command.durabilityboost
      aliases: [duraboost, dub]
   seen:
      description: Show information about the player
      permission: archecore.command.seen
   ipsearch:
      description: Searches matches for provided IP
      permission: archecore.command.ipsearch

permissions:
  archecore.arsql:
    description: Do not use unless you understand EXPLICITLY what you are doing. If you read this permission and do not next to instantly recognise it, don't fucking give it to yourself. Thanks.
  archecore.vanillabeacon:
    description: Override the beacon menu of Archecore and access a vanilla beacon when interacting with them.
  archecore.admin:
    description: Gives access to all facilities within Archecore
    default: op
    children:
      archecore.mod: true
      archecore.mod.economy: true
      archecore.persona.gender: true
      archecore.command.treasurechest: true
      archecore.persona.switchprofession: true
      archecore.exempt: true
      archecore.personas.15: true
      archecore.multilogin: true
  archecore.exempt:
    description: Exempts a player from being required to have a persona. Dangerous, high-level permission - use with caution
  archecore.mod:
    description: Gives moderator level access to facilities within archecore.
    children:
      archecore.mod.persona: true
      archecore.mod.sign: true
      archecore.money: true
      archecore.money.seeother: true
      archecore.command.newbies: true
      archecore.command.beaconme: true
      archecore.command.seen: true
      archecore.persona.setrace: true
      archecore.persona.realrace: true
      archecore.mayuse: true
  archecore.multilogin:
    description: Can use multiple Minecraft toons linked to the same account
  archecore.command.skin.nocooldown:
    description: Removes the cooldown on being able to switch skins
  archecore.command.skin.4:
    description: Unlocks 4 skins for a player to be able to use
    children:
      archecore.command.skin.3: true
  archecore.command.skin.3:
    description: Unlocks 3 skins for a player to be able to use
    children:
      archecore.command.skin.2: true
  archecore.command.skin.2:
    description: Unlocks 2 skins for a player to be able to use
    children:
      archecore.command.skin.1: true
  archecore.command.skin.1:
    description: Gives the player an additional skin they can use freely.
  archecore.mod.economy:
    description: Grants moderator-level access over economy facilities
    children:
      archecore.money: true
      archecore.money.seeother: true
  archecore.mod.persona:
    description: Gives the ability to edit personas as a moderator
    children:
      archecore.mod.other: true
      archecore.persona.realrace: true
      archecore.command.persona.construct: true
      archecore.command.persona.spectre: true
      archecore.command.persona.necrolyte: true
      archecore.command.persona.ascended: true
      archecore.persona.longbio: true
      archecore.persona.longname: true
      archecore.persona.quickrename: true
      archecore.persona.quickswitch: true
      archecore.persona.nonnewbie: true
      archecore.persona.quickkill: true
      archecore.command.persona.*: true
  archecore.mod.other:
    description: Allows the editting of persona cards which aren't your own.
  archecore.persona.quickkill:
    description: Allows the ability to bypass the no-permakill timer of creating a new persona
  archecore.persona.nonnewbie:
    description: Prevents a player from having the PvP protection a new persona has.
  archecore.persona.quickswitch:
    description: Gives the ability to switch personas quickly.
  archecore.persona.quickrename:
    description: Gives the ability to change your name quickly
  archecore.persona.longname:
    description: Gives the ability to have a longer than usual name
  archecore.persona.longbio:
    description: Gives the ability to have a longer than usual biography
  archecore.persona.switchprofession:
    description: Gives the ability to switch the profession of either your or another persona
  archecore.admin.command.persona.permakill:
    description: No description
  archecore.admin.command.persona.assignrace:
    description: No description
  archecore.admin.command.persona.assigngender:
    description: No description
  archecore.command.persona.setrace:
    description: Gain access to /persona setrace
    default: op
  archecore.command.persona.openinv:
    description: Gain access to /persona openinv
    default: op
  archecore.command.persona.openender:
    description: Gain access to /persona openender
    default: op
  archecore.command.persona.setrace:
    description: Gives the ability to set the race of a persona
  archecore.command.persona.construct:
    description: Gives the ability to set a persona to a construct
  archecore.command.persona.spectre:
    description: Gives the ability to set a persona to a spectre
  archecore.command.persona.necrolyte:
    description: Gives the ability to set a persona to a necrolyte
  archecore.command.persona.ascended:
    description: Gives the ability to set a persona to an Aengulbound
  archecore.command.persona.name:
    description: Gain access to /persona name
    default: yes
  archecore.command.persona.prefix:
    description: Gain access to /persona prefix if prefixes are enabled.
    default: yes
  archcecore.command.persona.prefix.clear:
    description: Gain access to /persona clearprefix if prefixes are enabled
    default: yes
  archecore.command.persona.time:
    description: Gain access to /persona time
    default: yes
  archecore.command.persona.age:
    description: Gain access to /persona age
  archecore.command.persona.profession:
    description: Gain access to /persona profession
    default: yes
  archecore.command.persona.list:
    description: Gain access to /persona list
    default: yes
  archecore.command.persona.desc:
    description: Gain access to /persona setinfo and /persona addinfo
    default: yes
  archecore.command.persona.icon:
    description: Give access to /persona icon
    default: yes
  archecore.command.persona.created:
    description: Give access to /persona created
    default: yes

  archecore.command.persona.view.more:
    description: Gain access to view more persona info with /persona more
    default: yes
  archecore.command.persona.view:
    description: Gain access to /persona view
    default: yes
  archecore.command.persona.help:
    description: Gain access to /persona help.
    default: yes
  archecore.money:
    description: Gives access to use /money and it's aliases for managing money if the Economy module is enabled.
    default: yes
  archecore.money.seeother:
    description: Gives the ability to view the funds of another persona than your own
  archecore.command.beaconme:
    description: Gives accesss to the command /beaconme or accessing a beacon menu to edit and create personas.
    default: yes
  archecore.enderchest:
    description: Gives access to your personal ender chest which can be used freely on the run after you have achieved a certain number of hours on a persona.
    default: yes
  archecore.mayuse:
    description: The base permission required for nearly all facilities of Archecore, the Persona Framework.
    default: yes
