name: ArcheCore
main: net.lordofthecraft.arche.ArcheCore
authors: [Arche, Kowaman]
soft-depend: [PermissionsEx]
version: 1.83

commands:
   archehelp:
      description: Obtain help on various aspects of this Server! 
      usage: /<command> for a list of topics. Gain Help with /<command> [topic] 
   helpmenu: 
      description: Obtain Help in a convenient menu format!
   persona:
      description: Manage your Persona or Roleplay Character
      usage: Invalid syntax! Use /<command> help for a list of commands
      permission: archecore.mayuse
      permission-message: §4Insufficient Permission for this command
      aliases: [pers,prs,p]
   newbies:
     description: Allows you to scan for nearby new personas
     usage: This command can only be run from ingame.
     permission: archecore.command.newbies
     permission-messaage: §4Insufficient Permission for this command
     aliases: [newbie, new, n, ne]
   beaconme:
      description: Open the ArcheCore Beacon menu
      permission: archecore.command.beaconme
      permission-message: §4Insufficient Permission for this command
      aliases: [bme, me]    
   arsql:
      description: Execute SQL statements from ingame
   skill:
      description: Manage your Skills or teach others.
      usage: Invalid syntax! Use /<command> help for a list of commands
      permission: archecore.mayuse
      permission-message: §4Insufficient Permission for this command
      aliases: sk
   treasurechest:
      description: Handle the loot obtainable from the Treasure Chest items
      permission: archecore.command.treasurechest
      permission-message: §4Insufficient Permission for this command
      aliases: trch
   realname:
      description: get the current Minecraft Username from a Persona name.
      permission: archecore.mayuse
      permission-message: §4Insufficient Permission for this command
      aliases: [name, nick]
   autoage:
      description: Age all eligible (auto-aging) personas by 1 year
      permission: archecore.admin
      permission-message: §4Insufficient Permission for this command
   money:
      description: interact with the Persona-based money balance
      permission: archecore.money
      permission-message: §4Insufficient Permission for this command
      aliases: mn
      usage: Invalid syntax! Use /<command> help for a list of commands
   namelog:
      usage: /<command> [player name/uuid]
      description: interact with the Persona-based money balance
      permission: archecore.mod.persona
      permission-message: §4Insufficient Permission for this command
      